cat ../index.html > mainmenu.html
cat ../index.html > srchhelp_X_nojavascript.html
cat ../index.html > opacmenu.html
cat ../index.html > srchhelp_erm.html
cat ../index.html > srchhelp_a.html
cat ../index.html > srchhelp_b.html
cat ../index.html > srchhelp_c.html
cat ../index.html > srchhelp_d.html
cat ../index.html > srchhelp_e.html
cat ../index.html > srchhelp_f.html
cat ../index.html > srchhelp_g.html
cat ../index.html > srchhelp_h.html
cat ../index.html > srchhelp_i.html
cat ../index.html > srchhelp_j.html
cat ../index.html > srchhelp_k.html
cat ../index.html > srchhelp_l.html
cat ../index.html > srchhelp_m.html
cat ../index.html > srchhelp_n.html
cat ../index.html > srchhelp_o.html
cat ../index.html > srchhelp_p.html
cat ../index.html > srchhelp_q.html
cat ../index.html > srchhelp_r.html
cat ../index.html > srchhelp_s.html
cat ../index.html > srchhelp_t.html
cat ../index.html > srchhelp_u.html
cat ../index.html > srchhelp_v.html
cat ../index.html > srchhelp_w.html
cat ../index.html > srchhelp_x.html
cat ../index.html > srchhelp_y.html
cat ../index.html > srchhelp_z.html
cat ../index.html > srchhelp_A.html
cat ../index.html > srchhelp_B.html
cat ../index.html > srchhelp_C.html
cat ../index.html > srchhelp_D.html
cat ../index.html > srchhelp_E.html
cat ../index.html > srchhelp_F.html
cat ../index.html > srchhelp_G.html
cat ../index.html > srchhelp_H.html
cat ../index.html > srchhelp_I.html
cat ../index.html > srchhelp_J.html
cat ../index.html > srchhelp_K.html
cat ../index.html > srchhelp_L.html
cat ../index.html > srchhelp_M.html
cat ../index.html > srchhelp_N.html
cat ../index.html > srchhelp_O.html
cat ../index.html > srchhelp_P.html
cat ../index.html > srchhelp_Q.html
cat ../index.html > srchhelp_R.html
cat ../index.html > srchhelp_S.html
cat ../index.html > srchhelp_T.html
cat ../index.html > srchhelp_U.html
cat ../index.html > srchhelp_V.html
cat ../index.html > srchhelp_W.html
cat ../index.html > srchhelp_X.html
cat ../index.html > srchhelp_Y.html
cat ../index.html > srchhelp_Z.html